# Gui Helper

## Import [/import]

### Configure a new templates, devices and flows [POST /import]
Returns all currently configured flows
+ Request (application/json; charset=utf-8)
  + Headers

            Authorization: Bearer JWT

  + Body

            {
            }

+ Response 200 (application/json; charset=utf-8)

  + Body

            {
            }

+ Response 400 (application/json; charset=utf-8)

  + Body

            {
                "message": "message"
            }
